export const FETCH_COMMUNITIES_BEGIN = "communities/FETCH_COMMUNITIES_BEGIN";
export const FETCH_COMMUNITIES_END = "communities/FETCH_COMMUNITIES_END";
export const SELECT_COMMUNITY = "communities/SELECT_COMMUNITY";
export const FETCH_APARTMENTS_BEGIN = "apartments/FETCH_APARTMENTS_BEGIN";
export const FETCH_APARTMENTS_END = "apartments/FETCH_APARTMENTS_END";
export const SHOW_APARTMENT_UNIT_DATA = "apartments/SHOW_APARTMENT_UNIT_DATA";
export const HIDE_APARTMENT_UNIT_DATA = "apartments/HIDE_APARTMENT_UNIT_DATA";
export const SELECT_APARTMENT_UNIT = "apartments/SELECT_APARTMENT_UNIT";