export const FETCH_COMMUNITIES_BEGIN = "FETCH_COMMUNITIES_BEGIN";
export const FETCH_COMMUNITIES_END = "FETCH_COMMUNITIES_END";
export const SELECT_COMMUNITY = "SELECT_COMMUNITY";
export const FETCH_APARTMENTS_BEGIN = "FETCH_APARTMENTS_BEGIN";
export const FETCH_APARTMENTS_END = "FETCH_APARTMENTS_END";